version: "3.2"
services:
  web-dev:
    image: pablosaraiva/web:latest
    ports:
      - "8080"
  nginx-dev:
    image: nginx
    depends_on:
      - web-dev
    volumes:
      - "./nginx-dev.conf:/etc/nginx/nginx.conf"
      - "./${ACME_CHALLENGE_FILENAME}:/etc/acme-challenge/.well-known/acme-challenge/${ACME_CHALLENGE_FILENAME}"
      - "/etc/letsencrypt/live/pablosaraiva.com/fullchain.pem:/etc/ssl/certificate.pem"
      - "/etc/letsencrypt/live/pablosaraiva.com/privkey.pem:/etc/ssl/key.pem"
    ports:
      - "8080:443"
