version: 2.1

orbs:
  maven: circleci/maven@0.0.12

jobs:
  build-staging:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build . -t pablosaraiva/web:latest
            echo "$DOCKERHUB_PASS" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
            docker push pablosaraiva/web:latest

  build-prod:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build . -t pablosaraiva/web:stable
            echo "$DOCKERHUB_PASS" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
            docker push pablosaraiva/web:stable


workflows:
  build-master:
    jobs:
      - maven/test:
          filters:
            branches:
              only: master
      - build-prod:
          requires:
            - maven/test
          filters:
            branches:
              only: master

  build-develop:
    jobs:
      - maven/test:
          filters:
            branches:
              only: develop
      - build-staging:
          requires:
            - maven/test
          filters:
            branches:
              only: develop
